In [1]:
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt
import numpy as np
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [3]:
data = pd.read_csv('healthcare_dataset.csv')

In [5]:
data

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

In [9]:
data.isna().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [11]:
data.dropna(inplace=True)

In [13]:
data['Date of Admission'] = pd.to_datetime(data['Date of Admission'])
data['Discharge Date'] = pd.to_datetime(data['Discharge Date'])

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  datetime64[ns]
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  datetime64[ns]
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: datetime64[ns](2), float64(1), int64(2), object(10)
memory usage: 6.4+ MB

In [17]:
def change_to_date(column):
    data[column]=pd.to_datetime(data[column],infer_datetime_format=True)

In [19]:
for i in ['Date of Admission','Discharge Date']:
    change_to_date(i)

In [21]:
data['admission_date']=data['Date of Admission'].dt.day
data['admission_month']=data['Date of Admission'].dt.month
data['admission_year']=data['Date of Admission'].dt.year

In [23]:
data.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,admission_date,admission_month,admission_year
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal,31,1,2024
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,20,8,2019
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal,22,9,2022
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal,18,11,2020
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal,19,9,2022

In [25]:
data['discharge_date']=data['Discharge Date'].dt.day
data['discharge_month']=data['Discharge Date'].dt.month
data['discharge_year']=data['Discharge Date'].dt.year

In [27]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  datetime64[ns]
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  datetime64[ns]
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
 15  admission_date      55500 non-null  int32
 16  admission_month     55500 non-null  int32
 17  admission_year      55500 non-null  int32
 18  discharge_date      55500 non-null  int32
 19  discharge_month     55500 non-null  int32
 20  discharge_year      55500 non-null  int32
dtypes: datetime64[ns](2), float64(1), int32(6), int64(2), object(10)
memory usage: 7.6+ MB

In [29]:
drop_cloumn = ['Name','Doctor','Hospital','Room Number','Insurance Provider','Date of Admission','Discharge Date']

In [31]:
data.drop(columns=drop_cloumn,inplace=True)

In [33]:
data

,Age,Gender,Blood Type,Medical Condition,Billing Amount,Admission Type,Medication,Test Results,admission_date,admission_month,admission_year,discharge_date,discharge_month,discharge_year
0,30,Male,B-,Cancer,18856.281306,Urgent,Paracetamol,Normal,31,1,2024,2,2,2024
1,62,Male,A+,Obesity,33643.327287,Emergency,Ibuprofen,Inconclusive,20,8,2019,26,8,2019
2,76,Female,A-,Obesity,27955.096079,Emergency,Aspirin,Normal,22,9,2022,7,10,2022
3,28,Female,O+,Diabetes,37909.782410,Elective,Ibuprofen,Abnormal,18,11,2020,18,12,2020
4,43,Female,AB+,Cancer,14238.317814,Urgent,Penicillin,Abnormal,19,9,2022,9,10,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,42,Female,O+,Asthma,2650.714952,Elective,Penicillin,Abnormal,16,8,2020,15,9,2020
55496,61,Female,AB-,Obesity,31457.797307,Elective,Aspirin,Normal,23,1,2020,1,2,2020
55497,38,Female,B+,Hypertension,27620.764717,Urgent,Ibuprofen,Abnormal,13,7,2020,10,8,2020
55498,43,Male,O-,Arthritis,32451.092358,Elective,Ibuprofen,Abnormal,25,5,2019,31,5,2019
55499,53,Female,O+,Arthritis,4010.134172,Urgent,Ibuprofen,Abnormal,2,4,2024,29,4,2024

In [35]:
data['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [37]:
data['Gender'] = data['Gender'].map({'Female':0,'Male':1})

In [39]:
data

,Age,Gender,Blood Type,Medical Condition,Billing Amount,Admission Type,Medication,Test Results,admission_date,admission_month,admission_year,discharge_date,discharge_month,discharge_year
0,30,1,B-,Cancer,18856.281306,Urgent,Paracetamol,Normal,31,1,2024,2,2,2024
1,62,1,A+,Obesity,33643.327287,Emergency,Ibuprofen,Inconclusive,20,8,2019,26,8,2019
2,76,0,A-,Obesity,27955.096079,Emergency,Aspirin,Normal,22,9,2022,7,10,2022
3,28,0,O+,Diabetes,37909.782410,Elective,Ibuprofen,Abnormal,18,11,2020,18,12,2020
4,43,0,AB+,Cancer,14238.317814,Urgent,Penicillin,Abnormal,19,9,2022,9,10,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,42,0,O+,Asthma,2650.714952,Elective,Penicillin,Abnormal,16,8,2020,15,9,2020
55496,61,0,AB-,Obesity,31457.797307,Elective,Aspirin,Normal,23,1,2020,1,2,2020
55497,38,0,B+,Hypertension,27620.764717,Urgent,Ibuprofen,Abnormal,13,7,2020,10,8,2020
55498,43,1,O-,Arthritis,32451.092358,Elective,Ibuprofen,Abnormal,25,5,2019,31,5,2019
55499,53,0,O+,Arthritis,4010.134172,Urgent,Ibuprofen,Abnormal,2,4,2024,29,4,2024

In [41]:
data['Blood Type'].unique()

array(['B-', 'A+', 'A-', 'O+', 'AB+', 'AB-', 'B+', 'O-'], dtype=object)

In [43]:
data['Medication'].unique()

array(['Paracetamol', 'Ibuprofen', 'Aspirin', 'Penicillin', 'Lipitor'],
      dtype=object)

In [45]:
cat = data.select_dtypes(include='object').columns
num = data.select_dtypes(include=['int','float64']).columns

In [47]:
cat

Index(['Blood Type', 'Medical Condition', 'Admission Type', 'Medication',
       'Test Results'],
      dtype='object')

In [49]:
num

Index(['Age', 'Gender', 'Billing Amount', 'admission_date', 'admission_month',
       'admission_year', 'discharge_date', 'discharge_month',
       'discharge_year'],
      dtype='object')

In [51]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [53]:
for i in cat:
    data[i]=le.fit_transform(data[i])

In [55]:
data

,Age,Gender,Blood Type,Medical Condition,Billing Amount,Admission Type,Medication,Test Results,admission_date,admission_month,admission_year,discharge_date,discharge_month,discharge_year
0,30,1,5,2,18856.281306,2,3,2,31,1,2024,2,2,2024
1,62,1,0,5,33643.327287,1,1,1,20,8,2019,26,8,2019
2,76,0,1,5,27955.096079,1,0,2,22,9,2022,7,10,2022
3,28,0,6,3,37909.782410,0,1,0,18,11,2020,18,12,2020
4,43,0,2,2,14238.317814,2,4,0,19,9,2022,9,10,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,42,0,6,1,2650.714952,0,4,0,16,8,2020,15,9,2020
55496,61,0,3,5,31457.797307,0,0,2,23,1,2020,1,2,2020
55497,38,0,4,4,27620.764717,2,1,0,13,7,2020,10,8,2020
55498,43,1,7,0,32451.092358,0,1,0,25,5,2019,31,5,2019
55499,53,0,6,0,4010.134172,2,1,0,2,4,2024,29,4,2024

In [57]:
data['Billing Amount']= data['Billing Amount'].astype('int64')

In [59]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                55500 non-null  int64
 1   Gender             55500 non-null  int64
 2   Blood Type         55500 non-null  int32
 3   Medical Condition  55500 non-null  int32
 4   Billing Amount     55500 non-null  int64
 5   Admission Type     55500 non-null  int32
 6   Medication         55500 non-null  int32
 7   Test Results       55500 non-null  int32
 8   admission_date     55500 non-null  int32
 9   admission_month    55500 non-null  int32
 10  admission_year     55500 non-null  int32
 11  discharge_date     55500 non-null  int32
 12  discharge_month    55500 non-null  int32
 13  discharge_year     55500 non-null  int32
dtypes: int32(11), int64(3)
memory usage: 3.6 MB

data

In [61]:
X_cls= data.drop('Gender',axis=1)
y_cls = data['Gender']

In [63]:
from sklearn.model_selection import train_test_split

In [65]:
X_cls_train,X_cls_test,y_cls_train,y_cls_test = train_test_split(X_cls,y_cls,test_size=0.2)

In [67]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [69]:
lr.fit(X_cls_train,y_cls_train)

LogisticRegression()

In [71]:
y_pred = lr.predict(X_cls_test)

In [73]:
y_pred

array([1, 0, 0, ..., 1, 1, 1], dtype=int64)

In [75]:
from sklearn.metrics import accuracy_score

In [77]:
accuracy_score(y_cls_test,y_pred)

0.49423423423423424

In [79]:
from sklearn.ensemble import GradientBoostingClassifier
GBC = GradientBoostingClassifier()

In [81]:
GBC.fit(X_cls_train,y_cls_train)

GradientBoostingClassifier()

In [82]:
y_pred = GBC.predict(X_cls_test)

In [83]:
from sklearn.metrics import accuracy_score

In [84]:
accuracy_score(y_cls_test,y_pred)

0.5041441441441441

In [85]:
from sklearn.ensemble import AdaBoostClassifier,RandomForestClassifier

In [86]:
AD = AdaBoostClassifier()

In [93]:
AD.fit(X_cls_train,y_cls_train)

AdaBoostClassifier()

In [95]:
y_pred = AD.predict(X_cls_test)

In [97]:
accuracy_score(y_cls_test,y_pred)

0.4972072072072072

In [99]:
RFC = RandomForestClassifier()

In [101]:
RFC.fit(X_cls_train,y_cls_train)

RandomForestClassifier()

In [102]:
y_pred = RFC.predict(X_cls_test)

In [103]:
accuracy_score(y_cls_test,y_pred)

0.5763963963963964

In [46]:
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt
import numpy as np
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [3]:
data = pd.read_csv('healthcare_dataset.csv')

In [5]:
data

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [7]:
data['Test Results'].unique()

array(['Normal', 'Inconclusive', 'Abnormal'], dtype=object)

In [21]:
data['Gender'] = data['Gender'].map({'Female':0,'Male':1})

In [23]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  int64
dtypes: float64(1), int64(3), object(11)
memory usage: 6.4+ MB

In [25]:
data.dropna(inplace=True)

In [27]:
cat = data.select_dtypes(include=['object']).columns
num = data.select_dtypes(include=['float64','int64']).columns

In [29]:
cat

Index(['Name', 'Gender', 'Blood Type', 'Medical Condition',
       'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider',
       'Admission Type', 'Discharge Date', 'Medication'],
      dtype='object')

In [31]:
num

Index(['Age', 'Billing Amount', 'Room Number', 'Test Results'], dtype='object')

In [33]:
num = num.drop(['Gender'])
num

Index(['Billing Amount', 'Room Number'], dtype='object')

In [35]:
X_cls = data.drop(columns=['Gender'])
y_cls = data[['Gender']]

In [39]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.ensemble import AdaBoostClassifier,AdaBoostRegressor,GradientBoostingClassifier,GradientBoostingRegressor,RandomForestClassifier,RandomForestRegressor
from xgboost import XGBClassifier,XGBRegressor
from sklearn.metrics import accuracy_score,mean_squared_error,r2_score
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression,LinearRegression
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor

In [41]:
num_pipe = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='median')),
    ('scaler',StandardScaler())])


cat_pipe = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('onehot',OneHotEncoder(handle_unknown='ignore'))])

prep_pipe = ColumnTransformer(transformers=[
    ('num',num_pipe,num),
    ('cat',cat_pipe,cat)])


cls = {
    'AdaBoost':AdaBoostClassifier(random_state=42),
    'GradiantBoosting':GradientBoostingClassifier(random_state=42),
    'XGBoost':XGBClassifier(random_state=42,objective='reg:squarederror'),
    'DTC':DecisionTreeClassifier(),
    'LR':LinearRegression(),
    'RFC':RandomForestClassifier(),
    'knn_cl':KNeighborsClassifier(n_neighbors=5,metric='l2'),
    'LR':LogisticRegression()}

In [43]:
X_cls_train,X_cls_test,y_cls_train,y_cls_test = train_test_split(X_cls,y_cls,test_size=0.2)

In [45]:
for name,model in cls.items():
    print('=======')
    pipe = Pipeline(steps=[
    ('preprocessor',prep_pipe),
    ('model',model)
    ])
    pipe.fit(X_cls_train,y_cls_train)
    print('Fitting for',name,'Classification')
    y_pred = pipe.predict(X_cls_test)
    rmse = np.sqrt(mean_squared_error(y_cls_test,y_pred))
    acc = accuracy_score(y_cls_test,y_pred)
    print(f'{name}_rmse = {rmse}')
    print(f'{name}_acc = {acc}')
    print('______________________\n')

=======
Fitting for AdaBoost Classification
AdaBoost_rmse = 1.2900520277237792
AdaBoost_acc = 0.33765765765765765
______________________

=======
Fitting for GradiantBoosting Classification
GradiantBoosting_rmse = 1.2730045328043968
GradiantBoosting_acc = 0.34540540540540543
______________________

=======
Fitting for XGBoost Classification
XGBoost_rmse = 1.2391147668417988
XGBoost_acc = 0.35486486486486485
______________________

=======
Fitting for DTC Classification
DTC_rmse = 1.0595341488657233
DTC_acc = 0.4463063063063063
______________________

=======
Fitting for LR Classification
LR_rmse = 1.064031090787371
LR_acc = 0.4481081081081081
______________________

=======
Fitting for RFC Classification
RFC_rmse = 1.0688884518613355
RFC_acc = 0.4431531531531532
______________________

=======
Fitting for knn_cl Classification
knn_cl_rmse = 1.1262630547383095
knn_cl_acc = 0.37261261261261264
______________________