In [1]:
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt
import numpy as np
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [3]:
data = pd.read_csv('laptopPrice.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'laptopPrice.csv'

In [27]:
data

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [29]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              823 non-null    object
 1   processor_brand    823 non-null    object
 2   processor_name     823 non-null    object
 3   processor_gnrtn    823 non-null    object
 4   ram_gb             823 non-null    object
 5   ram_type           823 non-null    object
 6   ssd                823 non-null    object
 7   hdd                823 non-null    object
 8   os                 823 non-null    object
 9   os_bit             823 non-null    object
 10  graphic_card_gb    823 non-null    object
 11  weight             823 non-null    object
 12  warranty           823 non-null    object
 13  Touchscreen        823 non-null    object
 14  msoffice           823 non-null    object
 15  Price              823 non-null    int64
 16  rating             823 non-null    object
 17  Number of Ratings  823 non-null    int64
 18  Number of Reviews  823 non-null    int64
dtypes: int64(3), object(16)
memory usage: 122.3+ KB

In [31]:
data.isna().sum()

brand                0
processor_brand      0
processor_name       0
processor_gnrtn      0
ram_gb               0
ram_type             0
ssd                  0
hdd                  0
os                   0
os_bit               0
graphic_card_gb      0
weight               0
warranty             0
Touchscreen          0
msoffice             0
Price                0
rating               0
Number of Ratings    0
Number of Reviews    0
dtype: int64

In [33]:
data['price_cat'] = pd.qcut(data['Price'],q=3,labels=['low','median','high'])

In [35]:
data

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews,price_cat
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0,low
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5,low
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1,low
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0,median
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0,low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0,high
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0,high
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0,high
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0,high
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4,median

In [37]:
data['brand'].unique()

array(['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE'],
      dtype=object)

In [39]:
data.replace({'price_cat':{'low':0,'median':1,'high':2}},inplace=True)

In [41]:
cat = data.select_dtypes(include='object').columns
num = data.select_dtypes(include=['int','float64']).columns

In [43]:
cat

Index(['brand', 'processor_brand', 'processor_name', 'processor_gnrtn',
       'ram_gb', 'ram_type', 'ssd', 'hdd', 'os', 'os_bit', 'graphic_card_gb',
       'weight', 'warranty', 'Touchscreen', 'msoffice', 'rating'],
      dtype='object')

In [45]:
num

Index(['Price', 'Number of Ratings', 'Number of Reviews'], dtype='object')

In [47]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [49]:
for i in cat:
    data[i]=le.fit_transform(data[i])

In [51]:
data

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews,price_cat
0,1,1,1,0,2,1,0,1,2,1,0,0,3,0,0,34649,1,3,0,0
1,5,1,1,0,2,1,0,1,2,1,0,0,3,0,0,38999,2,65,5,0
2,5,1,1,0,2,1,0,1,2,1,0,0,3,0,0,39999,2,8,1,0
3,1,1,2,0,3,1,6,0,2,0,1,0,3,0,0,69990,2,0,0,1
4,1,1,0,7,2,1,0,3,2,1,0,0,3,0,0,26990,2,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,0,10,7,2,1,1,0,2,1,0,0,0,0,0,135990,2,0,0,2
819,1,0,10,7,2,1,1,0,2,1,0,0,0,0,0,144990,2,0,0,2
820,1,0,10,7,2,1,1,0,2,1,2,0,0,0,0,149990,2,0,0,2
821,1,0,10,7,2,1,1,0,2,1,2,0,0,0,0,142990,2,0,0,2
822,5,0,8,0,3,1,6,0,0,1,0,2,3,0,0,57490,3,18,4,1

In [53]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              823 non-null    int32
 1   processor_brand    823 non-null    int32
 2   processor_name     823 non-null    int32
 3   processor_gnrtn    823 non-null    int32
 4   ram_gb             823 non-null    int32
 5   ram_type           823 non-null    int32
 6   ssd                823 non-null    int32
 7   hdd                823 non-null    int32
 8   os                 823 non-null    int32
 9   os_bit             823 non-null    int32
 10  graphic_card_gb    823 non-null    int32
 11  weight             823 non-null    int32
 12  warranty           823 non-null    int32
 13  Touchscreen        823 non-null    int32
 14  msoffice           823 non-null    int32
 15  Price              823 non-null    int64
 16  rating             823 non-null    int32
 17  Number of Ratings  823 non-null    int64
 18  Number of Reviews  823 non-null    int64
 19  price_cat          823 non-null    category
dtypes: category(1), int32(16), int64(3)
memory usage: 71.8 KB

In [55]:
X_cls = data.drop('price_cat',axis=1)
y_cls = data['price_cat']

In [57]:
X_reg = data.drop('Price',axis=1)
y_reg = data['Price']

In [59]:
from sklearn.model_selection import train_test_split

In [61]:
X_cls_train,X_cls_test,y_cls_train,y_cls_test = train_test_split(X_cls,y_cls,test_size=0.2)
X_reg_train,X_reg_test,y_reg_train,y_reg_test = train_test_split(X_reg,y_reg,test_size=0.2)

In [63]:
from sklearn.linear_model import LogisticRegression,LinearRegression
lr = LogisticRegression()

In [65]:
lr.fit(X_cls_train,y_cls_train)

LogisticRegression()

In [67]:
y_pred = lr.predict(X_cls_test)

In [69]:
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [71]:
from sklearn.metrics import accuracy_score

In [73]:
accuracy_score(y_cls_test,y_pred)

0.26666666666666666

In [75]:
from sklearn.ensemble import GradientBoostingClassifier,GradientBoostingRegressor
GBC = GradientBoostingClassifier()

In [77]:
GBC.fit(X_cls_train,y_cls_train)

GradientBoostingClassifier()

In [78]:
y_pred = GBC.predict(X_cls_test)

In [79]:
from sklearn.metrics import accuracy_score,r2_score

In [80]:
accuracy_score(y_cls_test,y_pred)

0.5575757575757576

In [85]:
from sklearn.ensemble import AdaBoostClassifier,AdaBoostRegressor,RandomForestClassifier,RandomForestRegressor

In [87]:
AD = AdaBoostClassifier()

In [89]:
AD.fit(X_cls_train,y_cls_train)

AdaBoostClassifier()

In [91]:
y_pred = AD.predict(X_cls_test)

In [93]:
accuracy_score(y_cls_test,y_pred)

0.3333333333333333

In [95]:
RFC = RandomForestClassifier()

In [97]:
RFC.fit(X_cls_train,y_cls_train)

RandomForestClassifier()

In [99]:
y_pred = RFC.predict(X_cls_test)

In [101]:
accuracy_score(y_cls_test,y_pred)

0.5818181818181818

In [103]:
LR = LinearRegression()

In [105]:
LR.fit(X_reg_train,y_reg_train)

LinearRegression()

In [107]:
y_reg_pred = LR.predict(X_reg_test)

In [109]:
r2_score(y_reg_test,y_reg_pred)

0.6805634492722483

In [111]:
RFR = RandomForestRegressor()

In [113]:
RFR.fit(X_reg_train,y_reg_train)

RandomForestRegressor()

In [114]:
y_reg_pred = RFR.predict(X_reg_test)

In [117]:
y_reg_pred

array([ 93517.82      ,  85329.76      ,  95802.45      , 119307.1       ,
        36308.78      ,  39239.29      ,  64975.7       , 122145.275     ,
        70105.91      ,  48804.1       ,  42097.35      , 100845.31      ,
        64360.49      ,  65198.92      ,  73990.        ,  59400.65      ,
        25109.13333333,  42362.79      , 143892.42333333, 191361.47      ,
        65141.04      ,  66214.4       ,  60830.02      ,  60013.94      ,
        49345.36      ,  48580.38333333,  45306.19      ,  61624.19      ,
        89956.57      ,  39970.64333333, 110835.4972619 ,  65952.14833333,
        66554.52      ,  38500.86      ,  67122.48133333,  64897.08      ,
        47323.8       ,  72532.96      ,  62080.1       ,  98185.9585    ,
        44542.31333333,  63579.24      ,  64097.61      ,  66857.39      ,
       110296.36      , 167990.27333333, 123160.45      ,  23329.13333333,
        39627.55      ,  45696.04666667,  42963.66      , 155606.62666667,
        61684.98      , 132886.8       ,  95976.84983333,  85996.69      ,
        36004.78      ,  42428.2       ,  60451.19      ,  46660.42      ,
        24120.56619048,  43807.09      ,  40757.80666667,  46043.64      ,
        66037.41      ,  64700.99      ,  66883.47      , 166450.19      ,
        42879.04      ,  62981.51      , 108634.17      ,  61964.79      ,
       123186.43      ,  71531.75      ,  65368.63      ,  42964.79      ,
        64730.25      ,  47070.61      ,  61505.57      , 132959.34      ,
        68028.54      ,  68965.79      ,  63343.69      ,  60688.28      ,
        44435.52      ,  92890.        ,  70328.12      ,  95463.57      ,
        89437.56      ,  62303.25      ,  42547.79      , 209781.05      ,
        88700.84666667,  47582.84      ,  40120.64333333,  41676.26      ,
        90803.8425    ,  24780.4       , 110883.33333333,  39288.78      ,
        67918.54      , 122354.82      ,  62748.58      ,  64740.52      ,
        63956.72      ,  37685.        ,  24987.82857143,  40859.49666667,
        70538.57      , 129051.29857143, 119202.87      ,  95888.42      ,
        44703.52      ,  41636.1       , 130125.40416667, 150376.43333333,
        92632.3175    ,  50677.1       ,  63622.86      , 112633.3       ,
        66558.19      ,  66000.63      ,  63170.655     ,  67649.47      ,
        96303.93      ,  61036.19      ,  63394.7       ,  49337.35      ,
        49576.7       ,  66389.92      ,  26578.41      , 101017.805     ,
       103623.52      ,  46862.26      , 129504.03166667,  90824.24916667,
        93427.94      ,  45590.70333333,  63904.45      ,  68082.42      ,
        37949.25      ,  48645.59      ,  46960.15666667,  47134.07      ,
        61019.53      , 154491.77      , 124042.        ,  61669.16      ,
       131177.47      ,  49063.6       , 141447.73857143, 109891.04142857,
        42735.53      ,  66985.66      ,  49337.35      ,  40120.64333333,
        40312.7       , 121362.64      ,  67625.49      ,  65351.86      ,
        39418.3       , 136265.26666667,  63999.62      , 221793.33333333,
       149713.43      ])

In [119]:
r2_score(y_reg_test,y_reg_pred)

0.8795568839581459

In [121]:
GBR = GradientBoostingRegressor()

In [123]:
GBR.fit(X_reg_test,y_reg_test)

GradientBoostingRegressor()

In [125]:
y_reg_pred = GBR.predict(X_reg_test)

In [127]:
y_reg_pred

array([ 96551.29320382,  89938.19976728,  89471.95712091,  92474.5258019 ,
        39997.81055603,  37207.00004171,  71722.43163739,  87182.48958144,
        71602.70774812,  48753.78067466,  43645.94514669, 107208.84738331,
        65503.35319215,  63465.59158794,  65351.19262333,  62161.93793291,
        17738.70245501,  44107.25378247, 124442.10931061, 235221.82006872,
        65418.59917428,  64566.31556266,  58874.48926377,  58526.84607796,
        46555.11078461,  45458.34032714,  46529.99111553,  59612.540025  ,
        89274.51298085,  34569.41855749, 119622.73155335,  65959.18932561,
        74103.7366279 ,  41904.88848914,  66896.02367541,  64703.54217975,
        47856.52299008,  67604.63675085,  60642.86874771,  95128.42101582,
        38896.56691013,  63127.32725404,  65184.02166544,  76040.4438456 ,
        90331.51863986, 214280.90450635, 130649.12590023,  20873.02907401,
        38045.10866233,  43129.54601348,  42331.33145779, 107737.4724563 ,
        65391.99889336, 120158.07954593,  93643.73292302,  89767.4539555 ,
        40635.81041749,  42848.00076903,  64685.96683594,  46859.55490088,
        20757.0362299 ,  45654.15769675,  40789.34100827,  43869.90781974,
        55760.52729595,  64798.82747605,  66393.06108218, 179281.43068948,
        42854.95110511,  63772.28627099,  81736.11051765,  63575.31942062,
       110726.55180283,  65470.80926332,  65464.91773014,  45899.98123368,
        69954.9811711 ,  50691.82967638,  63770.95722041,  99821.98388081,
        62337.92691273,  75370.25486132,  63376.1442619 ,  60697.16411902,
        44501.89944297,  89702.2182867 ,  71303.65540005,  92988.22811774,
        93716.56758061,  64981.8820558 ,  44788.63208582, 264092.02131563,
        95015.27149166,  48291.88466805,  40924.25369929,  41688.60568009,
        93510.6485582 ,  24985.41733742, 112487.74450333,  41712.28700002,
        66678.52926869, 171620.33461712,  65979.14897891,  65012.04187158,
        64758.28221998,  42007.33686467,  21020.31562888,  37951.52794274,
        69308.33566999, 141536.05532305, 111125.01285296,  90346.26826984,
        45898.87307983,  41700.64912924, 127680.06941478, 146589.27625201,
        88762.34908503,  44610.88709317,  67794.59985   ,  87033.0637706 ,
        71274.37331009,  66791.71953302,  65136.33404296,  66452.09167432,
        87345.98484892,  66608.09038602,  65481.73226393,  45632.94514667,
        46883.3125028 ,  59969.45445958,  23225.67117391, 105641.53158292,
        90823.44709784,  45557.7099728 , 141306.7643582 ,  93090.15937566,
        96696.05840481,  40491.99112611,  65765.09052524,  65123.18045337,
        44024.15045724,  48857.8878909 ,  43993.09419057,  43670.14857404,
        63776.21823828, 169552.89447591, 126042.57122983,  60633.9137635 ,
       133919.91348422,  50404.37839326, 133711.84531576, 115272.9593682 ,
        42106.1790238 ,  68049.5582119 ,  45632.94514667,  36282.72436532,
        40371.37578587, 142312.36997793,  60063.20706395,  62965.89746967,
        37765.20322097, 122564.17893101,  68595.09880341, 236709.01856424,
       120509.32319362])

In [129]:
r2_score(y_reg_test,y_reg_pred)

0.9816495272645415

In [131]:
AR = AdaBoostRegressor()

In [133]:
AR.fit(X_reg_train,y_reg_train)

AdaBoostRegressor()

In [135]:
y_reg_pred = AR.predict(X_reg_test)

In [137]:
y_reg_test

710     98920
718     80990
754     84988
487     79990
641     33690
        ...
143     36990
615    124990
580     66990
620    243990
415    125394
Name: Price, Length: 165, dtype: int64

In [139]:
r2_score(y_reg_test,y_reg_pred)

0.48631670547942496

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings 
warnings.filterwarnings('ignore')
%matplotlib inline

In [3]:
data = pd.read_csv('laptopPrice.csv')

In [5]:
data

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              823 non-null    object
 1   processor_brand    823 non-null    object
 2   processor_name     823 non-null    object
 3   processor_gnrtn    823 non-null    object
 4   ram_gb             823 non-null    object
 5   ram_type           823 non-null    object
 6   ssd                823 non-null    object
 7   hdd                823 non-null    object
 8   os                 823 non-null    object
 9   os_bit             823 non-null    object
 10  graphic_card_gb    823 non-null    object
 11  weight             823 non-null    object
 12  warranty           823 non-null    object
 13  Touchscreen        823 non-null    object
 14  msoffice           823 non-null    object
 15  Price              823 non-null    int64
 16  rating             823 non-null    object
 17  Number of Ratings  823 non-null    int64
 18  Number of Reviews  823 non-null    int64
dtypes: int64(3), object(16)
memory usage: 122.3+ KB

In [9]:
data.isna().sum()

brand                0
processor_brand      0
processor_name       0
processor_gnrtn      0
ram_gb               0
ram_type             0
ssd                  0
hdd                  0
os                   0
os_bit               0
graphic_card_gb      0
weight               0
warranty             0
Touchscreen          0
msoffice             0
Price                0
rating               0
Number of Ratings    0
Number of Reviews    0
dtype: int64

In [11]:
data['price_cat'] = pd.qcut(data['Price'],q=3,labels=['low','median','high'])

In [13]:
data

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews,price_cat
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0,low
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5,low
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1,low
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0,median
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0,low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0,high
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0,high
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0,high
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0,high
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4,median

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              823 non-null    object
 1   processor_brand    823 non-null    object
 2   processor_name     823 non-null    object
 3   processor_gnrtn    823 non-null    object
 4   ram_gb             823 non-null    object
 5   ram_type           823 non-null    object
 6   ssd                823 non-null    object
 7   hdd                823 non-null    object
 8   os                 823 non-null    object
 9   os_bit             823 non-null    object
 10  graphic_card_gb    823 non-null    object
 11  weight             823 non-null    object
 12  warranty           823 non-null    object
 13  Touchscreen        823 non-null    object
 14  msoffice           823 non-null    object
 15  Price              823 non-null    int64
 16  rating             823 non-null    object
 17  Number of Ratings  823 non-null    int64
 18  Number of Reviews  823 non-null    int64
 19  price_cat          823 non-null    category
dtypes: category(1), int64(3), object(16)
memory usage: 123.2+ KB

In [17]:
data.replace({'price_cat':{'low':0,'median':1,'high':2}},inplace=True)

In [19]:
data

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews,price_cat
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5,0
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1,0
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0,1
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0,2
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0,2
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0,2
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0,2
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4,1

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              823 non-null    object
 1   processor_brand    823 non-null    object
 2   processor_name     823 non-null    object
 3   processor_gnrtn    823 non-null    object
 4   ram_gb             823 non-null    object
 5   ram_type           823 non-null    object
 6   ssd                823 non-null    object
 7   hdd                823 non-null    object
 8   os                 823 non-null    object
 9   os_bit             823 non-null    object
 10  graphic_card_gb    823 non-null    object
 11  weight             823 non-null    object
 12  warranty           823 non-null    object
 13  Touchscreen        823 non-null    object
 14  msoffice           823 non-null    object
 15  Price              823 non-null    int64
 16  rating             823 non-null    object
 17  Number of Ratings  823 non-null    int64
 18  Number of Reviews  823 non-null    int64
 19  price_cat          823 non-null    category
dtypes: category(1), int64(3), object(16)
memory usage: 123.2+ KB

In [23]:
data['price_cat'] = data['price_cat'].astype('int64')

In [25]:
cat = data.select_dtypes(include=['object']).columns
num = data.select_dtypes(include=['int','float']).columns

In [27]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              823 non-null    object
 1   processor_brand    823 non-null    object
 2   processor_name     823 non-null    object
 3   processor_gnrtn    823 non-null    object
 4   ram_gb             823 non-null    object
 5   ram_type           823 non-null    object
 6   ssd                823 non-null    object
 7   hdd                823 non-null    object
 8   os                 823 non-null    object
 9   os_bit             823 non-null    object
 10  graphic_card_gb    823 non-null    object
 11  weight             823 non-null    object
 12  warranty           823 non-null    object
 13  Touchscreen        823 non-null    object
 14  msoffice           823 non-null    object
 15  Price              823 non-null    int64
 16  rating             823 non-null    object
 17  Number of Ratings  823 non-null    int64
 18  Number of Reviews  823 non-null    int64
 19  price_cat          823 non-null    int64
dtypes: int64(4), object(16)
memory usage: 128.7+ KB

In [29]:
cat

Index(['brand', 'processor_brand', 'processor_name', 'processor_gnrtn',
       'ram_gb', 'ram_type', 'ssd', 'hdd', 'os', 'os_bit', 'graphic_card_gb',
       'weight', 'warranty', 'Touchscreen', 'msoffice', 'rating'],
      dtype='object')

In [31]:
num

Index(['Price', 'Number of Ratings', 'Number of Reviews', 'price_cat'], dtype='object')

In [33]:
num = num.drop(['Price','price_cat'])

In [35]:
X_cls = data.drop(columns=['price_cat'])
y_cls = data[['price_cat']]

In [37]:
X_reg = data.drop(columns=['Price'])
y_reg = data[['Price']]

In [39]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.ensemble import AdaBoostClassifier,AdaBoostRegressor,GradientBoostingClassifier,GradientBoostingRegressor,RandomForestClassifier,RandomForestRegressor
from xgboost import XGBClassifier,XGBRegressor
from sklearn.metrics import accuracy_score,mean_squared_error,r2_score
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression,LinearRegression
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor

In [40]:
X_cls_train,X_cls_test,y_cls_train,y_cls_test = train_test_split(X_cls,y_cls,test_size=0.2)
X_reg_train,X_reg_test,y_reg_train,y_reg_test = train_test_split(X_reg,y_reg,test_size=0.2)

In [41]:
num_pipe = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='median')),
    ('scaler',StandardScaler())])


cat_pipe = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('onehot',OneHotEncoder(handle_unknown='ignore'))])

prep_pipe = ColumnTransformer(transformers=[
    ('num',num_pipe,num),
    ('cat',cat_pipe,cat)])


cls = {
    'AdaBoost':AdaBoostClassifier(random_state=42),
    'GradiantBoosting':GradientBoostingClassifier(random_state=42),
    'XGBoost':XGBClassifier(random_state=42,objective='reg:squarederror'),
    'DTC':DecisionTreeClassifier(),
    'LR':LinearRegression(),
    'RFC':RandomForestClassifier(),
    'knn_cl':KNeighborsClassifier(n_neighbors=5,metric='l2'),
    'LR':LogisticRegression()}


reg = {
    'AdaBoost':AdaBoostRegressor(random_state=42),
    'GradiantBoosting':GradientBoostingRegressor(random_state=42),
    'XGBoost':XGBRegressor(random_state=42,objective='reg:squarederror'),
    'LR':LinearRegression(),
    'DTR':DecisionTreeRegressor(),
    'knn_rg':KNeighborsRegressor(n_neighbors=5,metric='l2'),
    'RFR':RandomForestRegressor()}

In [45]:
for name,model in cls.items():
    print('=======')
    pipe = Pipeline(steps=[
    ('preprocessor',prep_pipe),
    ('model',model)
    ])
    pipe.fit(X_cls_train,y_cls_train)
    print('Fitting for',name,'Classification')
    y_pred = pipe.predict(X_cls_test)
    rmse = np.sqrt(mean_squared_error(y_cls_test,y_pred))
    acc = accuracy_score(y_cls_test,y_pred)
    print(f'{name}_rmse = {rmse}')
    print(f'{name}_acc = {acc}')
    print('______________________\n')

=======
Fitting for AdaBoost Classification
AdaBoost_rmse = 0.49848254581765294
AdaBoost_acc = 0.7696969696969697
______________________

=======
Fitting for GradiantBoosting Classification
GradiantBoosting_rmse = 0.46709936649691375
GradiantBoosting_acc = 0.8
______________________

=======
Fitting for XGBoost Classification
XGBoost_rmse = 0.4403855060505442
XGBoost_acc = 0.8242424242424242
______________________

=======
Fitting for DTC Classification
DTC_rmse = 0.49848254581765294
DTC_acc = 0.7696969696969697
______________________

=======
Fitting for LR Classification
LR_rmse = 0.4605661864718383
LR_acc = 0.806060606060606
______________________

=======
Fitting for RFC Classification
RFC_rmse = 0.46709936649691375
RFC_acc = 0.8
______________________

=======
Fitting for knn_cl Classification
knn_cl_rmse = 0.49848254581765294
knn_cl_acc = 0.7696969696969697
______________________

In [47]:
for name,model in reg.items():
    print('=======')
    pipe = Pipeline(steps=[
    ('preprocessor',prep_pipe),
    ('model',model)
    ])
    pipe.fit(X_reg_train,y_reg_train)
    print('Fitting for',name,'regressor')
    y_pred = pipe.predict(X_reg_test)
    rmse = np.sqrt(mean_squared_error(y_reg_test,y_pred))
    r2 = r2_score(y_reg_test,y_pred)
    print(f'{name}_rmse = {rmse}')
    print(f'{name}_r2 = {r2}')
    print('______________________\n')

=======
Fitting for AdaBoost regressor
AdaBoost_rmse = 25942.86698953886
AdaBoost_r2 = 0.5068705403207029
______________________

=======
Fitting for GradiantBoosting regressor
GradiantBoosting_rmse = 15027.787114515419
GradiantBoosting_r2 = 0.8345315958158182
______________________

=======
Fitting for XGBoost regressor
XGBoost_rmse = 14725.908268948277
XGBoost_r2 = 0.8411127328872681
______________________

=======
Fitting for LR regressor
LR_rmse = 16601.170813763954
LR_r2 = 0.7980692555031192
______________________

=======
Fitting for DTR regressor
DTR_rmse = 22844.393125043072
DTR_r2 = 0.6176296041459929
______________________

=======
Fitting for knn_rg regressor
knn_rg_rmse = 15698.338383099754
knn_rg_r2 = 0.8194354946116799
______________________

=======
Fitting for RFR regressor
RFR_rmse = 15172.016934889867
RFR_r2 = 0.8313401740852553
______________________